package com.zhl.job.pojo;

public class BanknameList {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BANKNAME_LIST.BANKID
     *
     * @mbggenerated Fri Apr 07 10:24:49 CST 2017
     */
    private String bankid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BANKNAME_LIST.BANKNAME
     *
     * @mbggenerated Fri Apr 07 10:24:49 CST 2017
     */
    private String bankname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BANKNAME_LIST.BANKCODE
     *
     * @mbggenerated Fri Apr 07 10:24:49 CST 2017
     */
    private String bankcode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BANKNAME_LIST.BANKID
     *
     * @return the value of BANKNAME_LIST.BANKID
     *
     * @mbggenerated Fri Apr 07 10:24:49 CST 2017
     */
    public String getBankid() {
        return bankid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BANKNAME_LIST.BANKID
     *
     * @param bankid the value for BANKNAME_LIST.BANKID
     *
     * @mbggenerated Fri Apr 07 10:24:49 CST 2017
     */
    public void setBankid(String bankid) {
        this.bankid = bankid == null ? null : bankid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BANKNAME_LIST.BANKNAME
     *
     * @return the value of BANKNAME_LIST.BANKNAME
     *
     * @mbggenerated Fri Apr 07 10:24:49 CST 2017
     */
    public String getBankname() {
        return bankname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BANKNAME_LIST.BANKNAME
     *
     * @param bankname the value for BANKNAME_LIST.BANKNAME
     *
     * @mbggenerated Fri Apr 07 10:24:49 CST 2017
     */
    public void setBankname(String bankname) {
        this.bankname = bankname == null ? null : bankname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BANKNAME_LIST.BANKCODE
     *
     * @return the value of BANKNAME_LIST.BANKCODE
     *
     * @mbggenerated Fri Apr 07 10:24:49 CST 2017
     */
    public String getBankcode() {
        return bankcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BANKNAME_LIST.BANKCODE
     *
     * @param bankcode the value for BANKNAME_LIST.BANKCODE
     *
     * @mbggenerated Fri Apr 07 10:24:49 CST 2017
     */
    public void setBankcode(String bankcode) {
        this.bankcode = bankcode == null ? null : bankcode.trim();
    }
}